version: '3'
services:
  dm-weather-app-webapp:
    container_name: dm-weather-app-webapp
    image: dm-weather-app-webapp:1.0.0
    ports:
      - "127.0.0.1:3001:3000"
    restart: unless-stopped
    environment:
      NEXT_PUBLIC_BACKEND_SERVER_URL: http://172.162.240.33/dm-weather-app-backend
      NEXT_PUBLIC_WEATHER_DATA_PROVIDER: OpenWeather
      NEXT_PUBLIC_WEATHER_DATA_PROVIDER_HOMEPAGE: https://openweathermap.org/
      NEXT_PUBLIC_APP_VERSION: 1.0.0
      NEXT_PUBLIC_LAST_RELEASE_DATE: 06.02.2024
