name: NodeJS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installing dependencies
      run: |
        npm install

    - name: EsLint - Check linting
      run: |
        npm run lint

    - name: Build project
      run: |
        npm run build

    - name: Run App in Background
      run: |
        npm run start &

    - name: Run Tests (End To End Tests)
      run: |
        cypress run --headless

    - name: Printing Env Variables
      run: |
        cat ./.env

#    - name: Cypress run
#      uses: cypress-io/github-action@v4
#      with:
#        browser: chrome
#        build: npm run build
#        start: npm dev
#        wait-on: "http://localhost:3000"
      env:
        NEXT_PUBLIC_BACKEND_SERVER_HOST: ${{ secrets.NEXT_PUBLIC_BACKEND_SERVER_HOST }}
        NEXT_PUBLIC_BACKEND_SERVER_URL: ${{ secrets.NEXT_PUBLIC_BACKEND_SERVER_URL }}
        NEXT_PUBLIC_DM_TECH_STATION_ID: ${{ secrets.NEXT_PUBLIC_DM_TECH_STATION_ID }}

        
        
