name: NodeJS CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installing dependencies
      run: |
        npm install

    - name: EsLint - Check linting
      run: |
        npm run lint

    - name: Build project
      run: |
        npm run build

#    - name: Run Tests (End To End Tests)
#      run: |
#        npm run cypress:ci

    - name: Cypress run
      uses: cypress-io/github-action@v4
      with:
        start: npm start
        wait-on: 'http://[::1]:3000/'
        config: baseUrl=http://[::1]:3000/
        install: false
        parallel: false

        
        
