name: NodeJS CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Installing dependencies
      run: |
        npm install

    - name: EsLint - Check linting
      run: |
        npm run lint

    - name: Build project
      run: |
        npm install
        npm build

    - name: Run Tests (End To End Tests)
      run: |
        npm run cypress:ci
        
        
